---
- hosts: all
  vars:
    ansible_user: matt
    remote_user: matt
  roles:
    - { role: auto_dhclient_ubuntu, when: ansible_distribution == 'Ubuntu' }
    - { role: auto_dhclient_centos, when: ansible_distribution == "CentOS" }

