---
- hosts: test
  vars:
    ansible_user: root
    remote_user: matt
  roles:
    - { role: install_snmp_manager_ubuntu, when: ansible_distribution == 'Ubuntu' }
    - { role: install_snmp_manager_centos, when: ansible_distribution == "CentOS" }
