---
- hosts: all
  vars:
    remote_user: "{{ remote_user }}"
    java_major: "8"
    java_minor: "151"
  roles:
    - { role: install_java_ubuntu, when: ansible_distribution == 'Ubuntu' }
    - { role: install_java_centos, when: ansible_distribution == 'CentOS' }

