---
- hosts: host1
  become: true
  vars:
    remote_user: {{ remote_user }}
  roles:
    - { role: install_snmp_manager_ubuntu, when: ansible_distribution == 'Ubuntu' }
    - { role: install_snmp_manager_centos, when: ansible_distribution == "CentOS" }
