---
- hosts: centos
  vars:
    remote_user: "{{ remote_user }}"
    rouser: "userRO"
    rouser_passwd: "userRO123"
    rwuser: "userRW"
    rwuser_passwd: "userRW123"
  roles:
    - { role: snmp_agent_ubuntu, when: ansible_distribution == 'Ubuntu' }
    - { role: snmp_agent_centos, when: ansible_distribution == "CentOS" }

