all:
  hosts:
    host1:
      ansible_host: 192.168.52.138
      ansible_user: host1
      remote_user: host1
    host2:
      ansible_host: 192.168.52.139
      ansible_user: host2
      remote_user: host2
    host3:
      ansible_host: 192.168.52.140
    host4:
      ansible_host: 192.168.56.10
  vars:
    ansible_user: matt
    remote_user: matt
  children:
    ubuntu:
      hosts:
        host1:
        host2:
        host3:
    centos:
      hosts:
        host4:

