all:
  hosts:
    host1:
      ansible_host: 192.168.56.10
    host2:
      ansible_host: 192.168.52.140
  vars:
    ansible_user: matt
    remote_user: matt
  children:
    app:
      hosts:
        host1:
        host2:

