# This role configures dhclient to automatically renew ip
# address after machine reboot
---
- name: "Print interface name"
  debug:
    msg: "Interface name: {{ ansible_default_ipv4.interface }} "

- name: Check whether interface renew configuration on startup CentOS"
  command: awk /^ONBOOT\=yes/ /etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}
  register: boot_config
  changed_when: False
  when: ansible_distribution == "CentOS"

- name: "Print config"
  debug:
    msg: "config result: {{ boot_config.stdout }}"

- name: "Enable renewing interface configuration on startup CentOS"
  lineinfile:
    path: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"
    regexp: '^ONBOOT='
    line: 'ONBOOT=yes'
  become: true
  when: (ansible_distribution == "CentOS") and (boot_config.stdout == "")

- name: restart server
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true
  when: boot_config.stdout == ""

- name: waiting for the server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=120
  sudo: false
  when: boot_config.stdout == ""


