# This role installs java from binaries for specific user
# and adds it to .bash_profile or .bashrc
---
- name: "Check if java is already installed"
  stat: 
    path: "{{ ansible_env.HOME }}/{{ ansible_env.HOME }}/jdk1.{{ java_major }}.0_{{ java_minor }}"
  register: java_installed

- name: "Extract jdk binaries"
  unarchive:
    src: "jdk-{{ java_major }}u{{ java_minor }}-linux-x64.tar.gz"
    dest: "{{ ansible_env.HOME }}/"
  when: not java_installed.stat.exists

- name: "Add symbolic link to java directory"
  file:
    src: "{{ ansible_env.HOME }}/jdk1.{{ java_major }}.0_{{ java_minor }}"
    dest: "{{ ansible_env.HOME }}/jdk"
    state: link

- name: "Check JAVA_HOME in bashrc"
  command: awk /^JAVA_HOME/ {{ ansible_env.HOME }}/.bashrc
  register: java_home
  changed_when: False
  when: ansible_distribution ==  "Ubuntu"

- name: "Update bashrc on Ubuntu"
  blockinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    marker: "# Added by Ansible"
    insertafter: "export.*"
    content: |
      JAVA_HOME={{ ansible_env.HOME }}/jdk
      export PATH=$PATH:$JAVA_HOME/bin
  when: (ansible_distribution == "Ubuntu") and (java_home.stdout=="")

- name: "Make .bashrc executable"
  file:
    path: "{{ ansible_env.HOME }}/.bashrc"
    mode: "u+x"

- name: "Reload bashrc"
  shell: "{{ ansible_env.HOME }}/.bashrc"
  args:
    executable: /bin/bash
  when: (ansible_distribution == "Ubuntu")

