# This role configures dhclient to automatically renew ip
# address after machine reboot
---
- name: "Print interface name"
  debug:
    msg: "Interface name: {{ ansible_default_ipv4.interface }} "

- name: Check whether /etc/rc.local contains "sudo dhclient"
  command: awk /^sudo\ dhclient/ /etc/rc.local
  register: boot_config
  changed_when: False
  when: ansible_distribution == "Ubuntu"

- name: "Set default interface to refresh ip on boot Ubuntu"
  blockinfile:
    path: "/etc/rc.local"
    marker: "# Added by Ansible"
    insertafter: "#*"
    content: |
      sudo dhclient {{ ansible_default_ipv4.interface }}
      exit 0
  become: true
  when: (ansible_distribution == "Ubuntu") and (boot_config.stdout == "")

#- name: restart server
#  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
#  async: 1
#  poll: 0
#  become: true
#  ignore_errors: true
#  when: boot_config.stdout == ""

#- name: waiting for the server to come back
#  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=120
#  sudo: false
#  when: boot_config.stdout == ""

